name: connectpro_ultimate
description: "ConnectPro Ultimate - Complete social platform integrating all Phase 5 Firebase & Cloud concepts with production-ready architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.6

  # Firebase Core & Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  cloud_functions: ^4.6.3
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+16
  firebase_remote_config: ^4.3.17
  firebase_app_check: ^0.2.1+17

  # Authentication Providers
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  firebase_ui_auth: ^1.10.0
  firebase_ui_oauth_google: ^1.3.2
  firebase_ui_oauth_apple: ^1.2.17

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Networking & HTTP
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Image Handling & Media
  cached_network_image: ^3.3.0
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  photo_view: ^0.14.0
  video_player: ^2.8.1

  # UI Components & Theming
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0

  # Navigation
  go_router: ^12.1.3
  auto_route: ^7.8.4

  # Utilities
  intl: ^0.19.0
  timeago: ^3.6.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2

  # Encryption & Security
  crypto: ^3.0.3
  encrypt: ^5.0.1
  pointycastle: ^3.7.3

  # Permissions
  permission_handler: ^11.1.0

  # Local Notifications
  flutter_local_notifications: ^16.3.0

  # Performance & Monitoring
  sentry_flutter: ^7.14.0

  # Development Tools
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0

  # Testing Utilities (for test builds)
  mocktail: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1

  # Testing
  mocktail: ^1.0.2
  bloc_test: ^9.1.5
  integration_test:
    sdk: flutter
  patrol: ^3.6.1

  # Firebase Testing
  fake_cloud_firestore: ^2.4.6
  firebase_auth_mocks: ^0.13.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - .env

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# Flutter configuration
flutter_gen:
  output: lib/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

# Asset generation
flutter_assets:
  assets_path: assets/
  output_path: lib/core/gen/
  create_library_file: true

# Build configuration
targets:
  $default:
    builders:
      freezed:
        options:
          # Generates copyWith, toString, hashCode, == methods
          copy_with: true
          equal: true
          to_string: true
      injectable_generator:
        options:
          # Generate dependency injection configuration
          auto_register: true
      retrofit_generator:
        options:
          # Generate type-safe HTTP clients
          generate_to_string: true