name: notemaster_pro
description: "Professional note-taking app with dual storage backends (Hive & SQLite)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Hive Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # SQLite Storage  
  sqflite: ^2.3.3
  path: ^1.9.0
  
  # Shared Preferences
  shared_preferences: ^2.2.3
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  
  # File System
  path_provider: ^2.1.2
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.11
  
  # Core
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  
  # Testing
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/