name: authflow_pro
description: Production-ready authentication and theme management system demonstrating hybrid state management
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management - Hybrid Architecture
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.5
  provider: ^6.0.5
  
  # Data & Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Authentication & Security
  local_auth: ^2.1.6
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  
  # Network & API
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # UI & Theme
  google_fonts: ^6.1.0
  dynamic_color: ^1.6.6
  flex_color_scheme: ^7.3.1
  
  # Utils
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.1.0
  intl: ^0.18.1
  
  # Development
  flutter_lints: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700
