name: connectpro_ultimate_integration_testing
description: "ConnectPro Ultimate with comprehensive integration testing and advanced mocking - End-to-End Testing Excellence"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core Services
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.9
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  
  # UI Components
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  animations: ^2.0.11
  flutter_staggered_grid_view: ^0.7.0
  
  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  
  # Validation
  form_field_validator: ^1.1.0
  
  # Network
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  
  # Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Local Notifications
  flutter_local_notifications: ^16.3.2
  
  # Performance
  vm_service: ^13.0.0
  
  # Core
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Integration Testing Framework
  integration_test:
    sdk: flutter
  patrol: ^2.2.0
  flutter_driver:
    sdk: flutter
  
  # Unit Testing Excellence
  test: ^1.24.6
  mockito: ^5.4.2
  mockito_annotations: ^0.3.0
  
  # Advanced Mocking
  http_mock_adapter: ^0.6.1
  fake_async: ^1.3.1
  fake_cloud_firestore: ^2.4.2
  firebase_auth_mocks: ^0.13.0
  cloud_firestore_mocks: ^0.17.0
  
  # Firebase Testing
  firebase_core_platform_interface: ^5.0.0
  
  # State Management Testing
  bloc_test: ^9.1.5
  riverpod_test: ^2.0.0
  
  # Performance Testing
  flutter_test_ui: ^1.0.0
  integration_test_preview: ^0.0.1
  
  # Cross-Platform Testing
  flutter_platform_widgets: ^4.0.0
  device_info_plus: ^9.1.0
  
  # Test Data Generation
  faker: ^2.1.0
  
  # Network Testing
  http: ^1.1.0
  dio_test: ^0.1.0
  
  # Platform Testing
  plugin_platform_interface: ^2.1.7
  
  # Coverage and Analysis
  coverage: ^1.7.2
  lcov: ^6.1.0
  very_good_analysis: ^5.1.0
  
  # Reporting and Analytics
  test_coverage: ^0.4.3
  junitreport: ^3.1.0
  
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.4
  
  # Golden Tests
  golden_toolkit: ^0.15.0
  
  # Performance Profiling
  flutter_gherkin: ^3.0.0
  
  # Accessibility Testing
  flutter_accessibility_service: ^0.2.0
  
  # CI/CD Integration
  github_actions_toolkit: ^0.3.0
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/test_data/
    - assets/mock_data/
  
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
