name: newshub_ultimate
description: Production-ready news application demonstrating complete data integration patterns
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.5
  
  # Networking & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  connectivity_plus: ^4.0.2
  
  # Local Storage - Dual Backend
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Caching & Performance
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  
  # Search & Analytics
  collection: ^1.17.2
  
  # UI & Theme
  google_fonts: ^6.1.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  
  # Utils
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  uuid: ^4.1.0
  intl: ^0.18.1
  
  # Environment
  flutter_dotenv: ^5.1.0
  
  # Development
  flutter_lints: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Testing
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  retrofit_generator: ^8.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: NewsFont
      fonts:
        - asset: assets/fonts/NewsFont-Regular.ttf
        - asset: assets/fonts/NewsFont-Bold.ttf
          weight: 700
