name: lesson_11_inheritedwidget_provider
description: "Lesson 11: InheritedWidget & Provider - Professional e-commerce shopping application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # UI enhancements
  cupertino_icons: ^1.0.6
  
  # Utilities
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Testing with Provider
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Assets for shopping app illustrations
  assets:
    - assets/images/
    - assets/icons/
  
  # Custom fonts for enhanced typography
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700