name: connectpro_ultimate_production_monitoring
description: "ConnectPro Ultimate with comprehensive error handling and production monitoring - Production Monitoring Excellence"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core Services
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.9
  firebase_performance: ^0.9.3+9
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  
  # UI Components
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  animations: ^2.0.11
  flutter_staggered_grid_view: ^0.7.0
  
  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  
  # Network & HTTP
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  http: ^1.1.0
  
  # Storage & File System
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Device Information
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  battery_plus: ^5.0.2
  
  # Performance Monitoring
  vm_service: ^13.0.0
  
  # Error Reporting & Analytics
  sentry_flutter: ^7.18.0
  
  # Local Notifications
  flutter_local_notifications: ^16.3.2
  
  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Core
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Testing Framework
  test: ^1.24.6
  mockito: ^5.4.2
  mockito_annotations: ^0.3.0
  
  # Integration Testing
  integration_test:
    sdk: flutter
  patrol: ^2.2.0
  
  # Mocking
  fake_async: ^1.3.1
  fake_cloud_firestore: ^2.4.2
  firebase_auth_mocks: ^0.13.0
  
  # State Management Testing
  bloc_test: ^9.1.5
  riverpod_test: ^2.0.0
  
  # Performance Testing
  flutter_test_ui: ^1.0.0
  
  # Test Data Generation
  faker: ^2.1.0
  
  # Coverage
  coverage: ^1.7.2
  lcov: ^6.1.0
  very_good_analysis: ^5.1.0
  
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.4
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/config/
  
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
